// GENERATED by scripts/gen-codes.mjs from knowledge/diagnostic-codes.json. Do not edit.
export const CODE_LIBRARY_VERSION = "0.1.0";
export const CODES = Object.freeze({
 "M-201": {
  "category": "motor",
  "fault_code": null,
  "title": "Phase resistance imbalance",
  "meaning": "One phase-pair resistance differs from the others by more than this test profile allows.",
  "checks": [
   "Inspect the phase connectors and terminals for heat damage, corrosion or loose pins.",
   "Clean or reseat the connections and repeat the test.",
   "If the imbalance remains with good connections, suspect the phase wiring or a winding inside the motor."
  ],
  "draft": true
 },
 "M-202": {
  "category": "motor",
  "fault_code": null,
  "title": "Phase resistance above range",
  "meaning": "At least one phase-pair resistance is above this test profile's maximum.",
  "checks": [
   "Check for an open or high-resistance connection in the phase wiring or connector.",
   "Confirm the adapter and test leads are seated, then repeat the test.",
   "A reading far above range on one pair can indicate an open winding."
  ],
  "draft": true
 },
 "M-203": {
  "category": "motor",
  "fault_code": null,
  "title": "Phase resistance below range",
  "meaning": "At least one phase-pair resistance is below this test profile's minimum.",
  "checks": [
   "Inspect the phase wiring for insulation damage or melted sections that could short phases together.",
   "Disconnect the motor from the controller and repeat the test to rule out the controller.",
   "A persistent low reading can indicate a shorted winding."
  ],
  "draft": true
 },
 "M-301": {
  "category": "motor",
  "fault_code": null,
  "title": "Back-EMF imbalance",
  "meaning": "The back-EMF amplitude of one phase differs from the others by more than this test profile allows.",
  "checks": [
   "Repeat the test turning the wheel at a steady speed; uneven speed changes the readings.",
   "Inspect the phase connectors and wiring.",
   "If the imbalance repeats at steady speed, suspect a winding or magnet problem in the motor."
  ],
  "draft": true
 },
 "M-302": {
  "category": "motor",
  "fault_code": null,
  "title": "Back-EMF below range",
  "meaning": "At least one phase produced less back-EMF than this test profile expects.",
  "checks": [
   "Turn the wheel faster and more steadily, then repeat the test.",
   "Check the phase wiring for an open connection.",
   "Low output on all phases at the correct speed can indicate weakened magnets."
  ],
  "draft": true
 },
 "M-303": {
  "category": "motor",
  "fault_code": null,
  "title": "Back-EMF above range",
  "meaning": "At least one phase produced more back-EMF than this test profile expects.",
  "checks": [
   "The wheel was probably turned faster than the test expects. Repeat at a slower, steady speed.",
   "Confirm the selected profile matches this motor."
  ],
  "draft": true
 },
 "S-101": {
  "category": "sensor",
  "fault_code": null,
  "title": "Sensor output above range",
  "meaning": "The sensor signal is above this test profile's maximum.",
  "checks": [
   "Check whether the signal wire is shorted to the sensor supply.",
   "Confirm the sensor type and profile match (for example a 5 V versus 3.3 V sensor).",
   "An output stuck near the supply voltage suggests a failed sensor."
  ],
  "draft": true
 },
 "S-102": {
  "category": "sensor",
  "fault_code": null,
  "title": "Sensor output below range",
  "meaning": "The sensor signal is below this test profile's minimum.",
  "checks": [
   "Check the sensor supply and ground connections.",
   "Check whether the signal wire is open or shorted to ground.",
   "An output stuck near 0 V with a good supply suggests a failed sensor."
  ],
  "draft": true
 },
 "E-001": {
  "category": "instrument",
  "fault_code": 1,
  "title": "Stopped by STOP",
  "meaning": "The STOP control was active, so the test stopped and outputs turned off.",
  "checks": [
   "Release STOP when it is safe, reset the fault, then start again."
  ],
  "draft": true
 },
 "E-002": {
  "category": "instrument",
  "fault_code": 2,
  "title": "Hardware safety latch",
  "meaning": "The hardware safety latch removed permission for outputs.",
  "checks": [
   "Check the device for a hardware fault indication, then reset."
  ],
  "draft": true
 },
 "E-003": {
  "category": "instrument",
  "fault_code": 3,
  "title": "External voltage present",
  "meaning": "Voltage from the vehicle was detected where the test needs it absent, so outputs turned off.",
  "checks": [
   "Disconnect the battery and charger as the test requires and make sure the wheel is not turning, then reset."
  ],
  "draft": true
 },
 "E-004": {
  "category": "instrument",
  "fault_code": 4,
  "title": "Overcurrent",
  "meaning": "Current exceeded the device's limit and outputs turned off.",
  "checks": [
   "Check the adapter and connections for a short, then reset."
  ],
  "draft": true
 },
 "E-005": {
  "category": "instrument",
  "fault_code": 5,
  "title": "Instrument measurement invalid",
  "meaning": "The device's own measurement path reported invalid data.",
  "checks": [
   "Reseat the adapter and repeat. If it repeats, the device may need service."
  ],
  "draft": true
 },
 "E-006": {
  "category": "instrument",
  "fault_code": 6,
  "title": "Instrument routing invalid",
  "meaning": "The device's internal routing could not be confirmed.",
  "checks": [
   "Reset and repeat. If it repeats, the device may need service."
  ],
  "draft": true
 },
 "E-007": {
  "category": "instrument",
  "fault_code": 7,
  "title": "Configuration invalid",
  "meaning": "The output or profile configuration was rejected by the safety manager.",
  "checks": [
   "Check that the adapter matches the selected test, then reset."
  ],
  "draft": true
 },
 "E-008": {
  "category": "instrument",
  "fault_code": 8,
  "title": "Self-test failed",
  "meaning": "The device's self-test did not pass.",
  "checks": [
   "Restart the device. If it repeats, the device needs service."
  ],
  "draft": true
 },
 "E-009": {
  "category": "instrument",
  "fault_code": 9,
  "title": "Safety inputs not updating",
  "meaning": "The safety monitoring data became stale, so outputs turned off.",
  "checks": [
   "Reset and repeat. If it repeats, the device needs service."
  ],
  "draft": true
 },
 "E-010": {
  "category": "instrument",
  "fault_code": 10,
  "title": "Overvoltage",
  "meaning": "Voltage exceeded the device's limit and outputs turned off.",
  "checks": [
   "Check that the adapter and vehicle voltage are within the device's rating, then reset."
  ],
  "draft": true
 },
 "E-011": {
  "category": "instrument",
  "fault_code": 11,
  "title": "Internal error",
  "meaning": "The device detected an impossible internal state and turned outputs off.",
  "checks": [
   "Restart the device. Record the code if it repeats and contact support."
  ],
  "draft": true
 },
 "E-012": {
  "category": "instrument",
  "fault_code": 12,
  "title": "Watchdog",
  "meaning": "The device's supervision detected a timing failure and turned outputs off.",
  "checks": [
   "Restart the device. Record the code if it repeats and contact support."
  ],
  "draft": true
 },
 "E-032": {
  "category": "instrument",
  "fault_code": 32,
  "title": "Outputs not confirmed off",
  "meaning": "The device could not confirm that its outputs turned off, so it stopped before changing connections.",
  "checks": [
   "Use STOP, disconnect the vehicle and restart the device. The device needs service if this repeats."
  ],
  "draft": true
 },
 "E-033": {
  "category": "instrument",
  "fault_code": 33,
  "title": "Connection routing failed",
  "meaning": "The device could not set up its internal test connections.",
  "checks": [
   "Reset and repeat. If it repeats, the device may need service."
  ],
  "draft": true
 },
 "E-034": {
  "category": "instrument",
  "fault_code": 34,
  "title": "Test setup rejected",
  "meaning": "The device rejected this test's setup before measuring.",
  "checks": [
   "Check that the adapter matches the selected test."
  ],
  "draft": true
 },
 "E-035": {
  "category": "instrument",
  "fault_code": 35,
  "title": "Output permission denied",
  "meaning": "The safety manager did not allow the test's outputs to turn on.",
  "checks": [
   "Check for an active STOP or fault, reset if needed, and repeat."
  ],
  "draft": true
 },
 "E-036": {
  "category": "instrument",
  "fault_code": 36,
  "title": "Output state mismatch",
  "meaning": "The outputs did not match what the test expected.",
  "checks": [
   "Reset and repeat. Record the code if it repeats."
  ],
  "draft": true
 },
 "E-037": {
  "category": "instrument",
  "fault_code": 37,
  "title": "Measurement could not be read",
  "meaning": "The device could not read the measurement, so this test says nothing about the vehicle.",
  "checks": [
   "Reseat the adapter and test leads and repeat."
  ],
  "draft": true
 },
 "E-038": {
  "category": "instrument",
  "fault_code": 38,
  "title": "Measurement unusable",
  "meaning": "The measurement was invalid, out of date or from the wrong channel, so this test says nothing about the vehicle.",
  "checks": [
   "Reseat the adapter and test leads and repeat."
  ],
  "draft": true
 },
 "E-039": {
  "category": "instrument",
  "fault_code": 39,
  "title": "Test step timed out",
  "meaning": "A test step did not finish in time.",
  "checks": [
   "Check the connections and repeat."
  ],
  "draft": true
 },
 "E-040": {
  "category": "instrument",
  "fault_code": 40,
  "title": "Test cancelled",
  "meaning": "The test was cancelled before it finished.",
  "checks": [
   "Start the test again when ready."
  ],
  "draft": true
 },
 "E-041": {
  "category": "instrument",
  "fault_code": 41,
  "title": "Internal sequence error",
  "meaning": "The device detected a corrupted test sequence and turned outputs off.",
  "checks": [
   "Restart the device. Record the code if it repeats and contact support."
  ],
  "draft": true
 }
});
