// GENERATED by scripts/knowledge.mjs from knowledge/ (decision 0007). Do not edit.
// Reviewed and validated entries only; drafts stay internal.
export const KNOWLEDGE = {
 "schema_version": 1,
 "version": "0.1.0",
 "vehicles": [],
 "components": [],
 "connectors": [],
 "protocols": [],
 "fault_codes": [],
 "hash": "e6920e9fc19587d79e2210f5c178b7b40e196c82b07a56019bef29794e96cff1"
};
